### ISSUE TITLE
i have a problem 

### ISSUE THREAD

**Issue by 9SS9** [youlinkoperatingsystem/scam#66]
**i do all the steps in video 100%100 but when i click verify it tell me "This interaction failed"**

and the code show in visual studio "TypeError: channel.isTextBased is not a function
    at InteractionCreateAction.handle (C:\Users\knonn\Desktop\scam\node_modules\discord.js\src\client\actions\InteractionCreate.js:50:33)
    at Object.module.exports [as INTERACTION_CREATE] (C:\Users\knonn\Desktop\scam\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\knonn\Desktop\scam\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\knonn\Desktop\scam\node_modules\discord.js\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (C:\Users\knonn\Desktop\scam\node_modules\discord.js\src\client\websocket\WebSocketShard.js:328:10)
    at callListener (C:\Users\knonn\Desktop\scam\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\Users\knonn\Desktop\scam\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnMessage (C:\Users\knonn\Desktop\scam\node_modules\ws\lib\websocket.js:1178:20)"
    
    
    **can anyone help me ?**

**Comment by Parokshkeshari** [comment]
same issue. Its not working anymore

**Comment by ulnk** [comment]
yourPanda#2063

**Comment by youlinkoperatingsystem** [comment]
test

**Comment by ulnk** [comment]
https://github.com/youlinkoperatingsystem/scam/commit/772848009d77aecbdc8b97002019480be6822ccd Fixed this issue
